In [1]:
import yfinance as yf

In [4]:
symbole = "NVDA"

titre = yf.Ticker(symbole)

histo = titre.history(period = "max", auto_adjust = False)

print ("dimensions :", histo.shape)
print("colonnes :" , histo.columns.tolist())

dimensions : (6948, 8)
colonnes : ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'Dividends', 'Stock Splits']

In [5]:
histo.head()

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
1999-01-22 00:00:00-05:00,0.043750,0.048828,0.038802,0.041016,0.037559,2714688000,0.0,0.0
1999-01-25 00:00:00-05:00,0.044271,0.045833,0.041016,0.045313,0.041494,510480000,0.0,0.0
1999-01-26 00:00:00-05:00,0.045833,0.046745,0.041146,0.041797,0.038274,343200000,0.0,0.0
1999-01-27 00:00:00-05:00,0.041927,0.042969,0.039583,0.041667,0.038155,244368000,0.0,0.0
1999-01-28 00:00:00-05:00,0.041667,0.041927,0.041276,0.041536,0.038035,227520000,0.0,0.0

In [6]:
histo.tail()

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2026-08-31 00:00:00-04:00,218.869995,221.300003,216.210007,220.779999,220.779999,124702700,0.0,0.0
2026-09-01 00:00:00-04:00,216.750000,220.410004,215.100006,217.440002,217.440002,109756200,0.0,0.0
2026-09-02 00:00:00-04:00,218.789993,227.949997,218.479996,224.410004,224.410004,157104700,0.0,0.0
2026-09-03 00:00:00-04:00,226.020004,230.399994,224.750000,228.449997,228.449997,134681600,0.0,0.0
2026-09-04 00:00:00-04:00,231.089996,234.759995,229.630005,230.360001,230.360001,134946800,0.0,0.0

In [16]:
divisions = histo[histo["Stock Splits"] !=0]
print("divisions d'actions :")
print(divisions[["Close", "Adj Close", "Stock Splits"]])

divisions d'actions :
                                Close   Adj Close  Stock Splits
Date
2000-06-27 00:00:00-04:00    0.296875    0.271854           2.0
2001-09-10 00:00:00-04:00    0.315667    0.289062           2.0
2006-04-07 00:00:00-04:00    0.508833    0.465947           2.0
2007-09-11 00:00:00-04:00    0.864500    0.791638           1.5
2021-07-20 00:00:00-04:00   18.612000   18.547842           4.0
2024-06-10 00:00:00-04:00  121.790001  121.579613          10.0

In [20]:
dividendes = histo[histo["Dividends"] != 0]
print(len(dividendes) , "dividendes verses. Les cinq derniers : ")
print(dividendes[["Close" , "Adj Close", "Dividends"]].tail(5))

55 dividendes verses. Les cinq derniers :
                                Close   Adj Close  Dividends
Date
2025-06-11 00:00:00-04:00  142.830002  142.640015       0.01
2025-09-11 00:00:00-04:00  177.169998  176.944321       0.01
2025-12-04 00:00:00-05:00  183.380005  183.156616       0.01
2026-03-11 00:00:00-04:00  186.029999  185.813431       0.01
2026-06-04 00:00:00-04:00  218.660004  218.660004       0.25

In [31]:
derniere = divisions.index[-1]
position = histo.index.get_loc(derniere)
print()

print("les jours autour de la derniere divison: ")
print(histo.iloc[position-2 : position +2][["Close", "Adj Close" , "Stock Splits"]])

les jours autour de la derniere divison:
                                Close   Adj Close  Stock Splits
Date
2024-06-06 00:00:00-04:00  120.998001  120.788986           0.0
2024-06-07 00:00:00-04:00  120.888000  120.679169           0.0
2024-06-10 00:00:00-04:00  121.790001  121.579613          10.0
2024-06-11 00:00:00-04:00  120.910004  120.711044           0.0